### ISSUE TITLE
Hints about oled support

### ISSUE THREAD

**Issue by Zeioth** [greyhatmiddleman/crkbd-pimoroni-trackball#1]
Hi! I'm using your firmware and it works correctly! I also made the oled work on the left side, but it doesn't update it's state.

It seems you need an special transport to achieve this on the slave side. Fortunately it seems Drasha already wrote it. I haven't been able to make it work yet. Maybe you'll be more lucky.

https://www.reddit.com/r/olkb/comments/m31hcx/how_to_display_led_state_on_oled_on_the_slave_side/

**Comment by douglance** [comment]
@Zeioth Did you get it working?

**Comment by Zeioth** [comment]
I'm afraid I didin't. I have no experience writing transports.

**Comment by whitehatmiddleman** [comment]
I just updated my qmk fork, the fix is now available.
