### ISSUE TITLE
Speeding up trackball

### ISSUE THREAD

**Issue by douglance** [greyhatmiddleman/crkbd-pimoroni-trackball#3]
I'd like to be able to hold the right layer key to speed up the trackball. 

How would I go about doing that?

**Comment by whitehatmiddleman** [comment]
I'll have to take a look. I won't have time this week, but next to see if I can make some modifications for that.

**Comment by douglance** [comment]
If you could just point me in the right direction, I should be able to figure it out. Thanks!

**Comment by whitehatmiddleman** [comment]
Not really an advanced C developer, the code in the pimoroni_trackball.c is where I would start. I finally have cycles to look into this, but if you're able to come up with a solution, I can update the repo with the changes.

**Comment by douglance** [comment]
I haven't had a chance to look into this yet, but another thing that might be cool is using the trackball to move the caret while typing. 

So with a key held down the trackball would send arrow key presses according to the direction that its scrolled. 

It might be easier to get around a text document that way than using the mouse pointer.

**Comment by whitehatmiddleman** [comment]
I have a layer that navigates like vim and also use neovim, so I rarely need to use a mouse. Archlinux is my OS with bspwm as my windows manager so my fingers never leave the home row. The trackball helps me when I have to browse the web.

You are welcome to fork and make any necessary changes that fit your personal needs.

**Comment by whitehatmiddleman** [comment]
FYI, I've finally been able to update the code to allow accelerating when a layer key is held down, similar to the scrolling feature. Running some tests and refactoring. I should have the qmk firmware repo updated this week.

**Comment by whitehatmiddleman** [comment]
Updated the repo to accelerate mouse when the NAV layer key is pressed.  The scrolling feature is activated when the SYM layer is pressed. 

Please go ahead and pull the updated repo. Let me know if you run into any issues.

**Comment by douglance** [comment]
I updated to the new changes. It works great. Thanks!

**Comment by whitehatmiddleman** [comment]
Awesome!!!
