### ISSUE TITLE
Left side not compiling

### ISSUE THREAD

**Issue by sayit358** [greyhatmiddleman/crkbd-pimoroni-trackball#4]
I've tried using the keymap on your fork to test if the trackball would theoretically work, but the left side won't compile. The errors are all undefined references to the trackball functions:

`/usr/bin/avr-ld: .build/obj_crkbd_rev1_greyhatmiddleman_trackball_left/keyboards/c
rkbd/keymaps/greyhatmiddleman_trackball_left/keymap.o: in function 'keyboard_post_ini
t_user':
 | /home/sayit/Git/qmk_firmware/keyboards/crkbd/keymaps/greyhatmiddleman_tra
ckball_left/keymap.c:173: undefined reference to 'trackball_set_rgbw'`

**Comment by sayit358** [comment]
I'm gonna close this indefinitely or until I actually get the trackball. I didn't read this right (or at all):

> Basically the master hand, the one that has the usb connected, will have the working code for the pimoroni trackball.

Thanks for documenting this stuff! :heart:

**Comment by whitehatmiddleman** [comment]
Please be sure to use my entire qmk firmware fork. If you are using the
original QMK firmware repo and you just copied only my keymap folders, it
will not work. Recent changes to the original repo will break forks that
are behind.

When I have time I will merge with the upstream and do testing.
